### ISSUE TITLE
Entering a command breaks something.

### ISSUE THREAD

**Issue by EonTitan277** [bplaxco/mctools#1]
With this example, I'm going to use the commands "/help" and "tell" but this problem happens with any command.
After entering a command the "> " where I write a new command disappears and if I press the up arrow to retrieve a previously entered command ("/help") it will take the first 2 characters of that command and use them in place of the "> ". ("/h") Then if I press up again to go to another previous command ("tell") it will look like this "/htell" instead of "> tell".
Do you understand?
To get the "> " back I just have to press enter without writing a command.
This doesn't really cause any problems, the commands will still work properly, it's just a visual thing.

**Comment by bplaxco** [comment]
Pushed some changes in https://github.com/bplaxco/mctools/commit/b54a546bab705425c9766104641a3aee4f292bd5 to make things a little better. Might not fix everything though. Haven't had time to fully test.

**Comment by EonTitan277** [comment]
The issue seems to have been resolved in your latest changes. 👍
