### ISSUE TITLE
Writing commands can break sometimes?

### ISSUE THREAD

**Issue by EonTitan277** [bplaxco/mctools#2]
I didn't know what to name it, sorry.
This is the thing that I was telling you about last week. Here's a video, it could have been better but I hope it's you can understand what I mean from it.
[VIDEO](https://drive.google.com/file/d/1-0-Z9v1k8xM_j33sgiCSB0nOsNAtSgGT/view?usp=sharing)

**Comment by bplaxco** [comment]
Okay. I'll take a look.

**Comment by bplaxco** [comment]
Hey @Smasher277, I've updated [the script on a feature branch](https://raw.githubusercontent.com/bplaxco/mctools/master/connect). Try that out and let me know if that works for you.

(updated link after merge)

**Comment by EonTitan277** [comment]
that fixed it 👍
